# cookbook filename: bash_logout

# settings/bash_logout: execute on shell logout

# Clear the screen on logout to prevent information leaks, if not already
# set as an exit trap elsewhere
[ -n "$PS1" ] && clear
